services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 15

  api:
    build: .
    environment:
      PORT: 3000
      NODE_ENV: development
      DATABASE_URL: postgres://app:app@db:5432/appdb
      JWT_SECRET: change-me
    command: >
      sh -c "node -e \"console.log('API container pronto (app entra depois)')\" && tail -f /dev/null"
    ports: ["3000:3000"]
    depends_on:
      db:
        condition: service_healthy
